# Generated by Django 4.2.13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_validated',
            field=models.BooleanField(default=False, verbose_name='email validated'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_validated',
            field=models.BooleanField(default=False, verbose_name='phone number validated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True, verbose_name='hobbies'),
        ),
    ]
